window.ITEM_DATA = [
      { "category": "AMMO", "items": [
        { "name": "12 Gauge Buckshot", "code": "ammo.shotgun" },
        { "name": "12 Gauge Incendiary Shell", "code": "ammo.shotgun.fire" },
        { "name": "12 Gauge Slug", "code": "ammo.shotgun.slug" },
        { "name": "40mm HE Grenade", "code": "ammo.grenadelauncher.he" },
        { "name": "40mm Shotgun Round", "code": "ammo.grenadelauncher.buckshot" },
        { "name": "40mm Smoke Grenade", "code": "ammo.grenadelauncher.smoke" },
        { "name": "5.56 Rifle Ammo", "code": "ammo.rifle" },
        { "name": "Bone Arrow", "code": "arrow.bone" },
        { "name": "Explosive 5.56 Rifle Ammo", "code": "ammo.rifle.explosive" },
        { "name": "Fire Arrow", "code": "arrow.fire" },
        { "name": "Handmade Shell", "code": "ammo.handmade.shell" },
        { "name": "High Velocity Arrow", "code": "arrow.hv" },
        { "name": "High Velocity Rocket", "code": "ammo.rocket.hv" },
        { "name": "Homing Missile", "code": "ammo.rocket.seeker" },
        { "name": "HV 5.56 Rifle Ammo", "code": "ammo.rifle.hv" },
        { "name": "HV Pistol Ammo", "code": "ammo.pistol.hv" },
        { "name": "Incendiary 5.56 Rifle Ammo", "code": "ammo.rifle.incendiary" },
        { "name": "Incendiary Pistol Bullet", "code": "ammo.pistol.fire" },
        { "name": "Incendiary Rocket", "code": "ammo.rocket.fire" },
        { "name": "MLRS Rocket", "code": "ammo.rocket.mlrs" },
        { "name": "Nailgun Nails", "code": "ammo.nailgun.nails" },
        { "name": "Pistol Bullet", "code": "ammo.pistol" },
        { "name": "Rocket", "code": "ammo.rocket.basic" },
        { "name": "SAM Ammo", "code": "ammo.rocket.sam" },
        { "name": "Torpedo", "code": "submarine.torpedo.straight" },
        { "name": "Wooden Arrow", "code": "arrow.wooden" }
      ]},
      { "category": "WEAPONS", "items": [
        { "name": "Assault Rifle", "code": "rifle.ak" },
        { "name": "Beancan Grenade", "code": "grenade.beancan" },
        { "name": "Blunderbuss", "code": "blunderbuss" },
        { "name": "Bolt Action Rifle", "code": "rifle.bolt" },
        { "name": "Bone Club", "code": "bone.club" },
        { "name": "Bone Knife", "code": "knife.bone" },
        { "name": "Combat Knife", "code": "knife.combat" },
        { "name": "Compound Bow", "code": "bow.compound" },
        { "name": "Crossbow", "code": "crossbow" },
        { "name": "Custom SMG", "code": "smg.2" },
        { "name": "Double Barrel Shotgun", "code": "shotgun.double" },
        { "name": "Eoka Pistol", "code": "pistol.eoka" },
        { "name": "F1 Grenade", "code": "grenade.f1" },
        { "name": "Flame Thrower", "code": "flamethrower" },
        { "name": "Flashbang", "code": "grenade.flashbang" },
        { "name": "Handmade SMG", "code": "t1_smg" },
        { "name": "High Caliber Revolver", "code": "revolver.hc" },
        { "name": "HMLMG", "code": "hmlmg" },
        { "name": "Homing Missile Launcher", "code": "homingmissile.launcher" },
        { "name": "Hunting Bow", "code": "bow.hunting" },
        { "name": "L96 Rifle", "code": "rifle.l96" },
        { "name": "Longsword", "code": "longsword" },
        { "name": "LR-300 Assault Rifle", "code": "rifle.lr300" },
        { "name": "M249", "code": "lmg.m249" },
        { "name": "M39 Rifle", "code": "rifle.m39" },
        { "name": "M4 Shotgun", "code": "shotgun.m4" },
        { "name": "M92 Pistol", "code": "pistol.m92" },
        { "name": "Mace", "code": "mace" },
        { "name": "Machete", "code": "machete" },
        { "name": "Military Flamethrower", "code": "military flamethrower" },
        { "name": "Minigun", "code": "minigun" },
        { "name": "Molotov Cocktail", "code": "grenade.molotov" },
        { "name": "MP5A4", "code": "smg.mp5" },
        { "name": "Multiple Grenade Launcher", "code": "multiplegrenadelauncher" },
        { "name": "Nailgun", "code": "pistol.nailgun" },
        { "name": "Paddle", "code": "paddle" },
        { "name": "Prototype 17", "code": "pistol.prototype17" },
        { "name": "Pump Shotgun", "code": "shotgun.pump" },
        { "name": "Python Revolver", "code": "pistol.python" },
        { "name": "Revolver", "code": "pistol.revolver" },
        { "name": "Rocket Launcher", "code": "rocket.launcher" },
        { "name": "Salvaged Cleaver", "code": "salvaged.cleaver" },
        { "name": "Salvaged Sword", "code": "salvaged.sword" },
        { "name": "Semi-Automatic Pistol", "code": "pistol.semiauto" },
        { "name": "Semi-Automatic Rifle", "code": "rifle.semiauto" },
        { "name": "Skinning Knife", "code": "knife.skinning" },
        { "name": "SKS", "code": "rifle.sks" },
        { "name": "Spas-12 Shotgun", "code": "shotgun.spas12" },
        { "name": "Speargun", "code": "speargun" },
        { "name": "Stone Spear", "code": "spear.stone" },
        { "name": "Thompson", "code": "smg.thompson" },
        { "name": "Waterpipe Shotgun", "code": "shotgun.waterpipe" },
        { "name": "Wooden Spear", "code": "spear.wooden" },
        { "name": "4x Zoom Scope", "code": "weapon.mod.small.scope" },
        { "name": "Burst Module", "code": "weapon.mod.burstmodule" },
        { "name": "Extended Magazine", "code": "weapon.mod.extendedmags" },
        { "name": "Holosight", "code": "weapon.mod.holosight" },
        { "name": "Muzzle Boost", "code": "weapon.mod.muzzleboost" },
        { "name": "Muzzle Brake", "code": "weapon.mod.muzzlebrake" },
        { "name": "Simple Handmade Sight", "code": "weapon.mod.simplesight" },
        { "name": "Silencer", "code": "weapon.mod.silencer" },
        { "name": "Weapon Flashlight", "code": "weapon.mod.flashlight" },
        { "name": "Weapon Lasersight", "code": "weapon.mod.lasersight" }  
    ]},
      { "category": "CONSTRUCTION", "items": [
        { "name": "Armored Door", "code": "door.hinged.toptier" },
        { "name": "Armored Double Door", "code": "door.double.hinged.toptier" },
        { "name": "Barbed Wooden Barricade", "code": "barricade.woodwire" },
        { "name": "Building Plan", "code": "building.planner" },
        { "name": "Chainlink Fence", "code": "wall.frame.fence" },
        { "name": "Chainlink Fence Gate", "code": "wall.frame.fence.gate" },
        { "name": "Code Lock", "code": "lock.code" },
        { "name": "Concrete Barricade", "code": "barricade.concrete" },
        { "name": "Floor Grill", "code": "floor.grill" },
        { "name": "Floor Triangle Grill", "code": "floor.triangle.grill" },
        { "name": "Garage Door", "code": "wall.frame.garagedoor" },
        { "name": "High External Stone Gate", "code": "gates.external.high.stone" },
        { "name": "High External Wooden Gate", "code": "gates.external.high.wood" },
        { "name": "High External Stone Wall", "code": "wall.external.high.stone" },
        { "name": "High External Wooden Wall", "code": "wall.external.high" },
        { "name": "Key Lock", "code": "lock.key" },
        { "name": "Ladder Hatch", "code": "floor.ladder.hatch" },
        { "name": "Large Water Catcher", "code": "water.catcher.large" },
        { "name": "Metal Barricade", "code": "barricade.metal" },
        { "name": "Metal Horizontal Embrasure", "code": "shutter.metal.embrasure.a" },
        { "name": "Metal Shop Front", "code": "wall.frame.shopfront.metal" },
        { "name": "Metal Vertical Embrasure", "code": "shutter.metal.embrasure.b" },
        { "name": "Metal Window Bars", "code": "wall.window.bars.metal" },
        { "name": "Netting", "code": "wall.frame.netting" },
        { "name": "Prison Cell Gate", "code": "wall.frame.cell.gate" },
        { "name": "Prison Cell Wall", "code": "wall.frame.cell" },
        { "name": "Reinforced Glass Window", "code": "wall.window.bars.toptier" },
        { "name": "Sandbag Barricade", "code": "barricade.sandbags" },
        { "name": "Sheet Metal Door", "code": "door.hinged.metal" },
        { "name": "Sheet Metal Double Door", "code": "door.double.hinged.metal" },
        { "name": "Shop Front", "code": "wall.frame.shopfront" },
        { "name": "Small Water Catcher", "code": "water.catcher.small" },
        { "name": "Stone Barricade", "code": "barricade.stone" },
        { "name": "Strengthened Glass Window", "code": "wall.window.glass.reinforced" },
        { "name": "Tool Cupboard", "code": "cupboard.tool" },
        { "name": "Triangle Ladder Hatch", "code": "floor.triangle.ladder.hatch" },
        { "name": "Watch Tower", "code": "watchtower.wood" },
        { "name": "Wood Double Door", "code": "door.double.hinged.wood" },
        { "name": "Wood Shutters", "code": "shutter.wood.a" },
        { "name": "Wooden Barricade", "code": "barricade.wood" },
        { "name": "Wooden Barricade Cover", "code": "barricade.wood.cover" },
        { "name": "Wooden Door", "code": "door.hinged.wood" },
        { "name": "Wooden Frontier Bar Doors", "code": "door.double.hinged.bardoors" },
        { "name": "Wooden Ladder", "code": "ladder.wooden.wall" },
        { "name": "Wooden Window Bars", "code": "wall.window.bars.wood" }
      ]},
      { "category": "ITEMS", "items": [
        { "name": "Barbeque", "code": "bbq" },
        { "name": "Bath Tub Planter", "code": "bathtub.planter" },
        { "name": "Bed", "code": "bed" },
        { "name": "Bolts Single Item Rack", "code": "gunrack.single.1.horizontal" },
        { "name": "Bota Bag", "code": "botabag" },
        { "name": "Camp Fire", "code": "campfire" },
        { "name": "Chair", "code": "chair" },
        { "name": "Drop Box", "code": "dropbox" },
        { "name": "Fish Trophy", "code": "fishtrophy" },
        { "name": "Fridge", "code": "fridge" },
        { "name": "Furnace", "code": "furnace" },
        { "name": "Hitch & Trough", "code": "hitchtroughcombo" },
        { "name": "Horizontal Storage Barrel", "code": "storage_barrel_c" },
        { "name": "Horizontal Weapon Rack", "code": "gunrack.horizontal" },
        { "name": "Horns Single Item Rack", "code": "gunrack.single.3.horizontal" },
        { "name": "Horseshoe Single Item Rack", "code": "gunrack.single.2.horizontal" },
        { "name": "Kayak", "code": "kayak" },
        { "name": "Kits Machine", "code": "kits.machine" },
        { "name": "Lantern", "code": "lantern" },
        { "name": "Large Furnace", "code": "furnace.large" },
        { "name": "Large Hunting Trophy", "code": "huntingtrophylarge" },
        { "name": "Large Planter Box", "code": "planter.large" },
        { "name": "Large Wood Box", "code": "box.wooden.large" },
        { "name": "Locker", "code": "locker" },
        { "name": "Mail Box", "code": "mailbox" },
        { "name": "Minecart Planter", "code": "minecart.planter" },
        { "name": "Mixing Table", "code": "mixingtable" },
        { "name": "Repair Bench", "code": "box.repair.bench" },
        { "name": "Research Table", "code": "research.table" },
        { "name": "RHIB", "code": "rhib" },
        { "name": "Rocking Chair", "code": "rockingchair" },
        { "name": "Rowboat", "code": "rowboat" },
        { "name": "Rug Bear Skin", "code": "rug.bear" },
        { "name": "Rug", "code": "rug" },
        { "name": "Salvaged Shelves", "code": "shelves" },
        { "name": "Skull Fire Pit", "code": "skull_fire_pit" },
        { "name": "Sleeping Bag", "code": "sleepingbag" },
        { "name": "Small Hunting Trophy", "code": "huntingtrophysmall" },
        { "name": "Small Planter Box", "code": "planter.small" },
        { "name": "Small Oil Refinery", "code": "small.oil.refinery" },
        { "name": "Small Stash", "code": "stash.small" },
        { "name": "Stone Fireplace", "code": "fireplace.stone" },
        { "name": "Survival Fish Trap", "code": "fishtrap.small" },
        { "name": "Table", "code": "table" },
        { "name": "Tall Weapon Rack", "code": "gunrack_tall.horizontal" },
        { "name": "Torch Holder", "code": "torchholder" },
        { "name": "Triangle Planter Box", "code": "planter.triangle" },
        { "name": "Tuna Can Lamp", "code": "tunalight" },
        { "name": "Vending Machine", "code": "vending.machine" },
        { "name": "Vertical Storage Barrel", "code": "storage_barrel_b" },
        { "name": "Water Barrel", "code": "water.barrel" },
        { "name": "Water Purifier", "code": "water.purifier" },
        { "name": "Weapon Rack Stand", "code": "gunrack_stand" },
        { "name": "Wide Weapon Rack", "code": "gunrack_wide.horizontal" },
        { "name": "Wood Storage Box", "code": "box.wooden" },
        { "name": "Workbench Level 1", "code": "workbench1" },
        { "name": "Workbench Level 2", "code": "workbench2" },
        { "name": "Workbench Level 3", "code": "workbench3" }
      ]},
      { "category": "RESOURCES", "items": [
        { "name": "Animal Fat", "code": "fat.animal" },
        { "name": "Bone Fragments", "code": "bone.fragments" },
        { "name": "CCTV Camera", "code": "cctv.camera" },
        { "name": "Charcoal", "code": "charcoal" },
        { "name": "Cloth", "code": "cloth" },
        { "name": "Crude Oil", "code": "crude.oil" },
        { "name": "Diesel Fuel", "code": "diesel_barrel" },
        { "name": "Empty Can Of Beans", "code": "can.beans.empty" },
        { "name": "Empty Tuna Can", "code": "can.tuna.empty" },
        { "name": "Explosives", "code": "explosives" },
        { "name": "Fertilizer", "code": "fertilizer" },
        { "name": "Gun Powder", "code": "gunpowder" },
        { "name": "High Quality Metal", "code": "metal.refined" },
        { "name": "High Quality Metal Ore", "code": "hq.metal.ore" },
        { "name": "Horse Dung", "code": "horsedung" },
        { "name": "Human Skull", "code": "skull.human" },
        { "name": "Leather", "code": "leather" },
        { "name": "Low Grade Fuel", "code": "lowgradefuel" },
        { "name": "Metal Fragments", "code": "metal.fragments" },
        { "name": "Metal Ore", "code": "metal.ore" },
        { "name": "Plant Fiber", "code": "plantfiber" },
        { "name": "Salt Water", "code": "water.salt" },
        { "name": "Scrap", "code": "scrap" },
        { "name": "Stones", "code": "stones" },
        { "name": "Sulfur Ore", "code": "sulfur.ore" },
        { "name": "Sulfur", "code": "sulfur" },
        { "name": "Targeting Computer", "code": "targeting.computer" },
        { "name": "Water", "code": "water" },
        { "name": "Wolf Skull", "code": "skull.wolf" },
        { "name": "Wood", "code": "wood" }
      ]},
      { "category": "COMPONENTS", "items": [
        { "name": "Electric Fuse", "code": "fuse" },
        { "name": "Empty Propane Tank", "code": "propanetank" },
        { "name": "Gears", "code": "gears" },
        { "name": "Metal Blade", "code": "metalblade" },
        { "name": "Metal Pipe", "code": "metalpipe" },
        { "name": "Metal Spring", "code": "metalspring" },
        { "name": "MLRS Aiming Module", "code": "aiming.module.mlrs" },
        { "name": "Rifle Body", "code": "riflebody" },
        { "name": "Road Signs", "code": "roadsigns" },
        { "name": "Rope", "code": "rope" },
        { "name": "Semi Automatic Body", "code": "semibody" },
        { "name": "Sewing Kit", "code": "sewingkit" },
        { "name": "Sheet Metal", "code": "sheetmetal" },
        { "name": "SMG Body", "code": "smgbody" },
        { "name": "Tarp", "code": "tarp" },
        { "name": "Tech Trash", "code": "techparts" }
      ]},
      { "category": "ATTIRE", "items": [
        { "name": "Bandana Mask", "code": "mask.bandana" },
        { "name": "Bandit Guard Gear", "code": "attire.banditguard" },
        { "name": "Barrel Costume", "code": "barrelcostume" },
        { "name": "Baseball Cap", "code": "hat.cap" },
        { "name": "Beanie Hat", "code": "hat.beenie" },
        { "name": "Bone Armor", "code": "bone.armor.suit" },
        { "name": "Bone Helmet", "code": "deer.skull.mask" },
        { "name": "Boonie Hat", "code": "hat.boonie" },
        { "name": "Boots", "code": "shoes.boots" },
        { "name": "Bucket Helmet", "code": "bucket.helmet" },
        { "name": "Burlap Gloves", "code": "burlap.gloves.new" },
        { "name": "Burlap Headwrap", "code": "burlap.headwrap" },
        { "name": "Burlap Shirt", "code": "burlap.shirt" },
        { "name": "Burlap Shoes", "code": "burlap.shoes" },
        { "name": "Burlap Trousers", "code": "burlap.trousers" },
        { "name": "Candle Hat", "code": "hat.candle" },
        { "name": "Coffee Can Helmet", "code": "coffeecan.helmet" },
        { "name": "Crate Costume", "code": "cratecostume" },
        { "name": "Diving Fins", "code": "diving.fins" },
        { "name": "Diving Mask", "code": "diving.mask" },
        { "name": "Diving Tank", "code": "diving.tank" },
        { "name": "Frog Boots", "code": "boots.frog" },
        { "name": "Frontier Suit", "code": "hazmatsuit.frontier" },
        { "name": "Hazmat Suit", "code": "hazmatsuit" },
        { "name": "Heavy Plate Helmet", "code": "heavy.plate.helmet" },
        { "name": "Heavy Plate Jacket", "code": "heavy.plate.jacket" },
        { "name": "Heavy Plate Pants", "code": "heavy.plate.pants" },
        { "name": "Hide Boots", "code": "attire.hide.boots" },
        { "name": "Hide Halterneck", "code": "attire.hide.helterneck" },
        { "name": "Hide Pants", "code": "attire.hide.pants" },
        { "name": "Hide Poncho", "code": "attire.hide.poncho" },
        { "name": "Hide Skirt", "code": "attire.hide.skirt" },
        { "name": "Hide Vest", "code": "attire.hide.vest" },
        { "name": "Homing Missile Launcher", "code": "homingmissile.launcher" },
        { "name": "Hoodie", "code": "hoodie" },
        { "name": "Improvised Balaclava", "code": "mask.balaclava" },
        { "name": "Jacket", "code": "jacket" },
        { "name": "Large Backpack", "code": "largebackpack" },
        { "name": "Leather Gloves", "code": "burlap.gloves" },
        { "name": "Longsleeve T-Shirt", "code": "tshirt.long" },
        { "name": "Lumberjack Hoodie", "code": "lumberjack hoodie" },
        { "name": "Metal Chest Plate", "code": "metal.plate.torso" },
        { "name": "Metal Facemask", "code": "metal.facemask" },
        { "name": "Miners Hat", "code": "hat.miner" },
        { "name": "Night Vision Goggles", "code": "nightvisiongoggles" },
        { "name": "Pants", "code": "pants" },
        { "name": "Parachute", "code": "parachute" },
        { "name": "Party Hat", "code": "partyhat" },
        { "name": "Prisoner Hood", "code": "prinsonerhood" },
        { "name": "Riot Helmet", "code": "riot.helmet" },
        { "name": "Roadsign Gloves", "code": "roadsign.gloves" },
        { "name": "Road Sign Jacket", "code": "roadsign.jacket" },
        { "name": "Road Sign Kilt", "code": "roadsign.kilt" },
        { "name": "Shirt", "code": "shirt.collared" },
        { "name": "Shorts", "code": "pants.shorts" },
        { "name": "Small Backpack", "code": "smallbackpack" },
        { "name": "Snow Jacket", "code": "jacket.snow" },
        { "name": "Tactical Gloves", "code": "tactical.gloves" },
        { "name": "Tank Top", "code": "shirt.tanktop" },
        { "name": "T-Shirt", "code": "tshirt" },
        { "name": "Wetsuit", "code": "diving.wetsuit" },
        { "name": "Wolf Headdress", "code": "hat.wolf" },
        { "name": "Wood Armor Helmet", "code": "wood.armor.helmet" },
        { "name": "Wood Armor Pants", "code": "wood.armor.pants" },
        { "name": "Wood Chestplate", "code": "wood.armor.jacket" }
      ]},
      { "category": "TOOLS", "items": [
        { "name": "Binoculars", "code": "tool.binoculars" },
        { "name": "Birthday Cake", "code": "cakefiveyear" },
        { "name": "Chainsaw", "code": "chainsaw" },
        { "name": "Flare", "code": "flare" },
        { "name": "Flashlight", "code": "flashlight.held" },
        { "name": "Hammer", "code": "hammer" },
        { "name": "Handcuffs", "code": "handcuffs" },
        { "name": "Handmade Fishing Rod", "code": "fishingrod.handmade" },
        { "name": "Hatchet", "code": "hatchet" },
        { "name": "Jackhammer", "code": "jackhammer" },
        { "name": "Metal Detector", "code": "metal.detector" },
        { "name": "Pickaxe", "code": "pickaxe" },
        { "name": "Pipe Tool", "code": "pipetool" },
        { "name": "RF Transmitter", "code": "rf.detonator" },
        { "name": "Rock", "code": "rock" },
        { "name": "Salvaged Axe", "code": "axe.salvaged" },
        { "name": "Salvaged Hammer", "code": "hammer.salvaged" },
        { "name": "Salvaged Icepick", "code": "icepick.salvaged" },
        { "name": "Satchel Charge", "code": "explosive.satchel" },
        { "name": "Smoke Grenade", "code": "grenade.smoke" },
        { "name": "Spray Can", "code": "spraycan" },
        { "name": "Stone Hatchet", "code": "stonehatchet" },
        { "name": "Stone Pickaxe", "code": "stone.pickaxe" },
        { "name": "Supply Signal", "code": "supply.signal" },
        { "name": "Timed Explosive Charge", "code": "explosive.timed" },
        { "name": "Torch", "code": "torch" },
        { "name": "Wallpaper Tool", "code": "wallpaper.tool" },
        { "name": "Water Bucket", "code": "bucket.water" }
      ]},
      { "category": "MEDS & TEAS", "items": [] },
      { "category": "MEDICAL", "items": [
        { "name": "Anti-Radiation Pills", "code": "antiradpills" },
        { "name": "Bandage", "code": "bandage" },
        { "name": "Large Medkit", "code": "largemedkit" },
        { "name": "Medical Syringe", "code": "syringe.medical" }
      ]},
      { "category": "FOOD", "items": [
        { "name": "Anchovy", "code": "fish.anchovy" },
        { "name": "Apple", "code": "apple" },
        { "name": "Black Raspberries", "code": "black.raspberries" },
        { "name": "Blueberries", "code": "blueberries" },
        { "name": "Blue Berry", "code": "blue.berry" },
        { "name": "Blue Berry Clone", "code": "clone.blue.berry" },
        { "name": "Blue Berry Seed", "code": "seed.blue.berry" },
        { "name": "Burnt Bear Meat", "code": "bearmeat.burned" },
        { "name": "Burnt Chicken", "code": "chicken.burned" },
        { "name": "Burnt Deer Meat", "code": "deermeat.burned" },
        { "name": "Burnt Horse Meat", "code": "horsemeat.burned" },
        { "name": "Burnt Human Meat", "code": "humanmeat.burned" },
        { "name": "Burnt Pork", "code": "meat.pork.burned" },
        { "name": "Burnt Wolf Meat", "code": "wolfmeat.burned" },
        { "name": "Cactus Flesh", "code": "cactusflesh" },
        { "name": "Can of Beans", "code": "can.beans" },
        { "name": "Can of Tuna", "code": "can.tuna" },
        { "name": "Catfish", "code": "fish.catfish" },
        { "name": "Chocolate Bar", "code": "chocolate" },
        { "name": "Cooked Bear Meat", "code": "bearmeat.cooked" },
        { "name": "Cooked Chicken", "code": "chicken.cooked" },
        { "name": "Cooked Deer Meat", "code": "deermeat.cooked" },
        { "name": "Cooked Fish", "code": "fish.cooked" },
        { "name": "Cooked Horse Meat", "code": "horsemeat.cooked" },
        { "name": "Cooked Human Meat", "code": "humanmeat.cooked" },
        { "name": "Cooked Pork", "code": "meat.pork.cooked" },
        { "name": "Cooked Wolf Meat", "code": "wolfmeat.cooked" },
        { "name": "Corn", "code": "corn" },
        { "name": "Corn Clone", "code": "clone.corn" },
        { "name": "Corn Seed", "code": "seed.corn" },
        { "name": "Granola Bar", "code": "granolabar" },
        { "name": "Green Berry", "code": "green.berry" },
        { "name": "Green Berry Clone", "code": "clone.green.berry" },
        { "name": "Green Berry Seed", "code": "seed.green.berry" },
        { "name": "Grub", "code": "grub" },
        { "name": "Hemp Clone", "code": "clone.hemp" },
        { "name": "Hemp Seed", "code": "seed.hemp" },
        { "name": "Herring", "code": "fish.herring" },
        { "name": "Minnows", "code": "fish.minnows" },
        { "name": "Mushroom", "code": "mushroom" },
        { "name": "Orange Roughy", "code": "fish.orangeroughy" },
        { "name": "Pickles", "code": "jar.pickle" },
        { "name": "Potato", "code": "potato" },
        { "name": "Potato Clone", "code": "clone.potato" },
        { "name": "Potato Seed", "code": "seed.potato" },
        { "name": "Pumpkin", "code": "pumpkin" },
        { "name": "Pumpkin Plant Clone", "code": "clone.pumpkin" },
        { "name": "Pumpkin Seed", "code": "seed.pumpkin" },
        { "name": "Raw Bear Meat", "code": "bearmeat" },
        { "name": "Raw Chicken Breast", "code": "chicken.raw" },
        { "name": "Raw Deer Meat", "code": "deermeat.raw" },
        { "name": "Raw Fish", "code": "fish.raw" },
        { "name": "Raw Horse Meat", "code": "horsemeat.raw" },
        { "name": "Raw Human Meat", "code": "humanmeat.raw" },
        { "name": "Raw Pork", "code": "meat.boar" },
        { "name": "Raw Wolf Meat", "code": "wolfmeat.raw" },
        { "name": "Red Berry", "code": "red.berry" },
        { "name": "Red Berry Clone", "code": "clone.red.berry" },
        { "name": "Red Berry Seed", "code": "seed.red.berry" },
        { "name": "Salmon", "code": "fish.salmon" },
        { "name": "Sardine", "code": "fish.sardine" },
        { "name": "Small Shark", "code": "fish.smallshark" },
        { "name": "Small Trout", "code": "fish.troutsmall" },
        { "name": "Small Water Bottle", "code": "smallwaterbottle" },
        { "name": "Water Jug", "code": "waterjug" },
        { "name": "White Berry", "code": "white.berry" },
        { "name": "White Berry Clone", "code": "clone.white.berry" },
        { "name": "White Berry Seed", "code": "seed.white.berry" },
        { "name": "Worm", "code": "worm" },
        { "name": "Yellow Berry", "code": "yellow.berry" },
        { "name": "Yellow Berry Clone", "code": "clone.yellow.berry" },
        { "name": "Yellow Berry Seed", "code": "seed.yellow.berry" },
        { "name": "Yellow Perch", "code": "fish.yellowperch" },
        { "name": "Advanced Anti-Rad Tea", "code": "radiationresisttea.advanced" },
        { "name": "Advanced Healing Tea", "code": "healingtea.advanced" },
        { "name": "Advanced Max Health Tea", "code": "maxhealthtea.advanced" },
        { "name": "Advanced Ore Tea", "code": "oretea.advanced" },
        { "name": "Advanced Rad. Removal Tea", "code": "radiationremovetea.advanced" },
        { "name": "Advanced Scrap Tea", "code": "scraptea.advanced" },
        { "name": "Advanced Wood Tea", "code": "woodtea.advanced" },
        { "name": "Anti-Rad Tea", "code": "radiationresisttea" },
        { "name": "Basic Healing Tea", "code": "healingtea" },
        { "name": "Basic Max Health Tea", "code": "maxhealthtea" },
        { "name": "Basic Ore Tea", "code": "oretea" },
        { "name": "Basic Scrap Tea", "code": "scraptea" },
        { "name": "Basic Wood Tea", "code": "woodtea" },
        { "name": "Pure Anti-Rad Tea", "code": "radiationresisttea.pure" },
        { "name": "Pure Healing Tea", "code": "healingtea.pure" },
        { "name": "Pure Max Health Tea", "code": "maxhealthtea.pure" },
        { "name": "Pure Ore Tea", "code": "oretea.pure" },
        { "name": "Pure Rad. Removal Tea", "code": "radiationremovetea.pure" },
        { "name": "Pure Scrap Tea", "code": "scraptea.pure" },
        { "name": "Pure Wood Tea", "code": "woodtea.pure" },
        { "name": "Rad. Removal Tea", "code": "radiationremovetea" }  
    ]},
      { "category": "TRAPS", "items": [
        { "name": "Flame Turret", "code": "flameturret" },
        { "name": "Landmine", "code": "trap.landmine" },
        { "name": "SAM Site", "code": "samsite" },
        { "name": "Shotgun Trap", "code": "guntrap" },
        { "name": "Snap Trap", "code": "trap.bear" },
        { "name": "Wooden Floor Spikes", "code": "spikes.floor" }
      ]},
      { "category": "MISCELLANEOUS", "items": [
        { "name": "Blue Keycard", "code": "keycard_blue" },
        { "name": "Door Key", "code": "door.key" },
        { "name": "Green Keycard", "code": "keycard_green" },
        { "name": "Guitar", "code": "fun.guitar" },
        { "name": "Note", "code": "note" },
        { "name": "Red Keycard", "code": "keycard_red" }
      ]},
      { "category": "ELECTRICAL", "items": [
        { "name": "AND Switch", "code": "electric.andswitch" },
        { "name": "Audio Alarm", "code": "electric.audioalarm" },
        { "name": "Auto Turret", "code": "autoturret" },
        { "name": "Blocker", "code": "electric.blocker" },
        { "name": "Button", "code": "electric.button" },
        { "name": "Ceiling Light", "code": "ceilinglight" },
        { "name": "Computer Station", "code": "computerstation" },
        { "name": "Counter", "code": "electric.counter" },
        { "name": "Door Controller", "code": "electric.doorcontroller" },
        { "name": "Drone", "code": "drone" },
        { "name": "Electrical Branch", "code": "electrical.branch" },
        { "name": "Electric Furnace", "code": "electric.furnace" },
        { "name": "Electric Heater", "code": "electric.heater" },
        { "name": "Elevator", "code": "elevator" },
        { "name": "Flasher Light", "code": "electric.flasherlight" },
        { "name": "Fluid Combiner", "code": "fluid.combiner" },
        { "name": "Fluid Splitter", "code": "fluid.splitter" },
        { "name": "Fluid Switch & Pump", "code": "fluid.switch" },
        { "name": "HBHF Sensor", "code": "electric.hbhfsensor" },
        { "name": "Hose Tool", "code": "hosetool" },
        { "name": "Igniter", "code": "electric.igniter" },
        { "name": "Industrial Combiner", "code": "industrial.combiner" },
        { "name": "Industrial Conveyor", "code": "industrial.conveyor" },
        { "name": "Industrial Crafter", "code": "industrial.crafter" },
        { "name": "Industrial Splitter", "code": "industrial.splitter" },
        { "name": "Large Rechargeable Battery", "code": "electric.battery.rechargable.large" },
        { "name": "Large Solar Panel", "code": "electric.solarpanel.large" },
        { "name": "Laser Detector", "code": "electrical.laserdetector" },
        { "name": "Medium Rechargeable Battery", "code": "electric.battery.rechargable.medium" },
        { "name": "Memory Cell", "code": "electrical.memorycell" },
        { "name": "Modular Car Lift", "code": "modularcarlift" },
        { "name": "OR Switch", "code": "electric.orswitch" },
        { "name": "Powered Water Purifier", "code": "powered.water.purifier" },
        { "name": "Pressure Pad", "code": "electric.pressurepad" },
        { "name": "RAND Switch", "code": "electric.random.switch" },
        { "name": "Reactive Target", "code": "target.reactive" },
        { "name": "RF Broadcaster", "code": "electric.rf.broadcaster" },
        { "name": "RF Pager", "code": "rf_pager" },
        { "name": "RF Receiver", "code": "electric.rf.receiver" },
        { "name": "Root Combiner", "code": "electrical.combiner" },
        { "name": "Search Light", "code": "searchlight" },
        { "name": "Seismic Sensor", "code": "electric.seismicsensor" },
        { "name": "Siren Light", "code": "electric.sirenlight" },
        { "name": "Small Rechargeable Battery", "code": "electric.battery.rechargable.small" },
        { "name": "Small Generator", "code": "electric.fuelgenerator.small" },
        { "name": "Splitter", "code": "electric.splitter" },
        { "name": "Sprinkler", "code": "electric.sprinkler" },
        { "name": "Storage Adapter", "code": "storageadapter" },
        { "name": "Storage Monitor", "code": "storage.monitor" },
        { "name": "Switch", "code": "electric.switch" },
        { "name": "Tesla Coil", "code": "electric.teslacoil" },
        { "name": "Test Generator", "code": "electric.generator.small" },
        { "name": "Timer", "code": "electric.timer" },
        { "name": "Water Pump", "code": "waterpump" },
        { "name": "Wind Turbine", "code": "generator.wind.scrap" },
        { "name": "Wire Tool", "code": "wiretool" },
        { "name": "XOR Switch", "code": "electric.xorswitch" }
      ]},
      { "category": "VEHICLES", "items": [
        { "name": "Attack Helicopter", "code": "attackhelicopter" },
        { "name": "Hot Air Balloon", "code": "hotairballoon" },
        { "name": "Minicopter", "code": "minicopter" },
        { "name": "Transport Helicopter", "code": "scraptransporthelicopter" },
        { "name": "Bicycle", "code": "pedalbike" },
        { "name": "Tricycle", "code": "pedaltrike" },
        { "name": "Motorbike", "code": "motorbike" },
        { "name": "Motorbike with Sidecar", "code": "motorbike_sidecar" },
        { "name": "2 Module Car", "code": "2module_car" },
        { "name": "3 Module Car", "code": "3module_car" },
        { "name": "4 Module Car", "code": "4module_car" },
        { "name": "Magnet Crane", "code": "magnetcrane" }
      ]},
      { "category": "VEHICLE MODULES", "items": [
        { "name": "Armored Cockpit Vehicle Module", "code": "vehicle.1mod.cockpit.armored" },
        { "name": "Armored Passenger Vehicle Module", "code": "vehicle.1mod.passengers.armored" },
        { "name": "Camper Vehicle Module", "code": "vehicle.2mod.camper" },
        { "name": "Cockpit Vehicle Module", "code": "vehicle.1mod.cockpit" },
        { "name": "Cockpit With Engine Vehicle Module", "code": "vehicle.1mod.cockpit.with.engine" },
        { "name": "Engine Vehicle Module", "code": "vehicle.1mod.engine" },
        { "name": "Flatbed Vehicle Module", "code": "vehicle.1mod.flatbed" },
        { "name": "Fuel Tank Vehicle Module", "code": "vehicle.2mod.fuel.tank" },
        { "name": "Large Flatbed Vehicle Module", "code": "vehicle.2mod.flatbed" },
        { "name": "Passenger Vehicle Module", "code": "vehicle.2mod.passengers" },
        { "name": "Rear Seats Vehicle Module", "code": "vehicle.1mod.rear.seats" },
        { "name": "Storage Vehicle Module", "code": "vehicle.1mod.storage" },
        { "name": "Taxi Vehicle Module", "code": "vehicle.1mod.taxi" }
      ]},
      { "category": "VEHICLE ENGINE PARTS", "items": [
        { "name": "Low Quality Carburetor", "code": "carburetor1" },
        { "name": "Medium Quality Carburetor", "code": "carburetor2" },
        { "name": "High Quality Carburetor", "code": "carburetor3" },
        { "name": "Low Quality Crankshaft", "code": "crankshaft1" },
        { "name": "Medium Quality Crankshaft", "code": "crankshaft2" },
        { "name": "High Quality Crankshaft", "code": "crankshaft3" },
        { "name": "Low Quality Pistons", "code": "piston1" },
        { "name": "Medium Quality Pistons", "code": "piston2" },
        { "name": "High Quality Pistons", "code": "piston3" },
        { "name": "Low Quality Spark Plugs", "code": "sparkplug1" },
        { "name": "Medium Quality Spark Plugs", "code": "sparkplug2" },
        { "name": "High Quality Spark Plugs", "code": "sparkplug3" },
        { "name": "Low Quality Valves", "code": "valve1" },
        { "name": "Medium Quality Valves", "code": "valve2" },
        { "name": "High Quality Valves", "code": "valve3" }
      ]},
      { "category": "EASTER", "items": [
        { "name": "Bronze Egg", "code": "easter.bronzeegg" },
        { "name": "Bunny Ears", "code": "attire.bunnyears" },
        { "name": "Bunny Onesie", "code": "attire.bunny.onesie" },
        { "name": "Egg Basket", "code": "easterbasket" },
        { "name": "Gold Egg", "code": "easter.goldegg" },
        { "name": "Painted Egg", "code": "easter.paintedeggs" },
        { "name": "Silver Egg", "code": "easter.silveregg" }
      ]},
      { "category": "HALLOWEEN", "items": [
        { "name": "Butcher Knife", "code": "knife.butcher" },
        { "name": "Coffin", "code": "coffin.storage" },
        { "name": "Gravestone", "code": "gravestone" },
        { "name": "Graveyard Fence", "code": "wall.graveyard.fence" },
        { "name": "Halloween Candy", "code": "halloween.candy" },
        { "name": "Large Loot Bag", "code": "halloween.lootbag.large" },
        { "name": "Medium Loot Bag", "code": "halloween.lootbag.medium" },
        { "name": "Mummy Suit", "code": "halloween.mummysuit" },
        { "name": "Pitchfork", "code": "pitchfork" },
        { "name": "Pumpkin Bucket", "code": "pumpkinbasket" },
        { "name": "Scarecrow", "code": "scarecrow" },
        { "name": "Scarecrow Suit", "code": "scarecrow.suit" },
        { "name": "Scarecrow Wrap", "code": "scarecrowhead" },
        { "name": "Sickle", "code": "sickle" },
        { "name": "Small Loot Bag", "code": "halloween.lootbag.small" },
        { "name": "Spider Webs", "code": "spiderweb" },
        { "name": "Wooden Cross", "code": "woodcross" }
      ]},
      { "category": "CHRISTMAS / XMAS", "items": [
        { "name": "Candy Cane", "code": "candycane" },
        { "name": "Candy Cane Club", "code": "candycaneclub" },
        { "name": "Christmas Lights", "code": "xmas.lightstring" },
        { "name": "Christmas Tree", "code": "xmas.tree" },
        { "name": "Coal", "code": "coal" },
        { "name": "Decorative Baubles", "code": "xmas.decoration.baubels" },
        { "name": "Decorative Gingerbread Men", "code": "xmas.decoration.gingerbreadmen" },
        { "name": "Decorative Pinecones", "code": "xmas.decoration.pinecone" },
        { "name": "Decorative Plastic Candy Canes", "code": "xmas.decoration.candycanes" },
        { "name": "Decorative Tinsel", "code": "xmas.decoration.tinsel" },
        { "name": "Gingerbread Suit", "code": "gingerbreadsuit" },
        { "name": "High Ice Wall", "code": "wall.external.high.ice" },
        { "name": "Large Present", "code": "xmas.present.large" },
        { "name": "Large Stocking", "code": "stocking.large" },
        { "name": "Medium Present", "code": "xmas.present.medium" },
        { "name": "Pookie Bear", "code": "pookie.bear" },
        { "name": "Reindeer Antlers", "code": "attire.reindeer.headband" },
        { "name": "Santa Hat", "code": "santahat" },
        { "name": "Short Ice Wall", "code": "wall.ice.wall" },
        { "name": "Small Present", "code": "xmas.present.small" },
        { "name": "Small Stocking", "code": "stocking.small" },
        { "name": "Snowball", "code": "snowball" },
        { "name": "Snowball Gun", "code": "snowballgun" },
        { "name": "Star Tree Topper", "code": "xmas.decoration.star" },
        { "name": "Tree Lights", "code": "xmas.decoration.lights" }
      ]}
    ];
